### ISSUE TITLE
Add an option for clients to disable downloading meshes

### ISSUE THREAD

**Issue by Periapsises** [shadowscion/Prop2Mesh#35]
Like you can disable rendering for custom meshes, an option that lets players select whether they want to download the meshes or not might help with client performance if you already keep rendering off  most of the time.

**Comment by shadowscion** [comment]
sounds great but opens the door to 'cheating' in contraption combat gamemodes

**Comment by wrefgtzweve** [comment]
What about a option for servers to allow or disallow it? a server convar would work for this

**Comment by shadowscion** [comment]
You could disable it to reveal internals like acf components or other weak points. 

The box is generated on the client using the min,max mesh vertices, after the data has already been transmitted anyway. The server doesn't know anything about this.

**Comment by shadowscion** [comment]
Alright, it is done

server convar: **'prop2mesh_disable_allowed 1/0'**
client convar: **'prop2mesh_disable 1/0'**

additional convar that renders cubes instead of obj content: **'prop2mesh_render_disable_obj 1/0'**

Neither of these will work with meshes that are already generated, you'll have to reconnect in that case.
